name: Super Vidya Staging

on:
  push:
    branches: ['staging']

jobs:
  deploy:
    runs-on: [self-hosted, staging]

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: 'false'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Prisma generate
        run: npm run db:generate

      - name: Prisma Migrate
        run: npm run db:migrate:test

      - name: Build application
        run: npm run build

      - name: Start server with PM2
        run: npm run start:staging
